CREATE TABLE IF NOT EXISTS user_preference (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    VARCHAR(64)  NOT NULL,
    category   VARCHAR(16)  NOT NULL,
    content    VARCHAR(500) NOT NULL,
    created_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_user_content   UNIQUE (user_id, content),
    CONSTRAINT ck_category       CHECK (category IN ('USER', 'FEEDBACK', 'PROJECT', 'REFERENCE')),
    CONSTRAINT ck_content_length CHECK (LENGTH(content) BETWEEN 1 AND 500)
    );

CREATE INDEX IF NOT EXISTS idx_pref_user ON user_preference (user_id, category);